/// <reference types="node" />
import { defineFunction } from '@aws-amplify/backend';
import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';

// The Lambda bundler can't load .wasm or .cedar files, so embed the Cedar
// engine and the policy text into a generated module (gitignored) at
// synth time, before the handler is bundled.
const here = (p: string) => fileURLToPath(new URL(p, import.meta.url));
const wasm = createRequire(import.meta.url)
  .resolve('@cedar-policy/cedar-wasm/nodejs')
  .replace(/nodejs\/cedar_wasm\.js$/, 'web/cedar_wasm_bg.wasm');
writeFileSync(
  here('./embedded.gen.ts'),
  `// Generated by resource.ts -- do not edit.\n` +
    `export const POLICY = ${JSON.stringify(readFileSync(here('./confirm.cedar'), 'utf8'))}\n` +
    `export const CEDAR_WASM_BASE64 = '${readFileSync(wasm).toString('base64')}'\n`,
);

export const confirmSlot = defineFunction({
  name: 'confirm-slot',
  entry: './handler.ts',
  timeoutSeconds: 30,
  memoryMB: 512,
  resourceGroupName: 'data',
});
